/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/': RouteRecordInfo<
      '/development/',
      '/development',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/development-standards': RouteRecordInfo<
      '/development/development-standards',
      '/development/development-standards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/first-step': RouteRecordInfo<
      '/development/first-step',
      '/development/first-step',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/setup-environment': RouteRecordInfo<
      '/development/setup-environment',
      '/development/setup-environment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/framework/': RouteRecordInfo<
      '/framework/',
      '/framework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/framework/adapt-liteloaderqqnt': RouteRecordInfo<
      '/framework/adapt-liteloaderqqnt',
      '/framework/adapt-liteloaderqqnt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/framework/event-archive': RouteRecordInfo<
      '/framework/event-archive',
      '/framework/event-archive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/framework/feedback': RouteRecordInfo<
      '/framework/feedback',
      '/framework/feedback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/framework/get-framework': RouteRecordInfo<
      '/framework/get-framework',
      '/framework/get-framework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/framework/open-source': RouteRecordInfo<
      '/framework/open-source',
      '/framework/open-source',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-press@1.1.0_vue@3.5.43_typescript@7.0.2_/node_modules/valaxy-theme-press/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'node_modules/.pnpm/valaxy@1.1.0_@devframes+age_eda448f33cc96cd27ac84aa6203ef873/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/development/index.md': {
      routes:
        | '/development/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/development/development-standards.md': {
      routes:
        | '/development/development-standards'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/development/first-step.md': {
      routes:
        | '/development/first-step'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/development/setup-environment.md': {
      routes:
        | '/development/setup-environment'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/framework/index.md': {
      routes:
        | '/framework/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/framework/adapt-liteloaderqqnt.md': {
      routes:
        | '/framework/adapt-liteloaderqqnt'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/framework/event-archive.md': {
      routes:
        | '/framework/event-archive'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/framework/feedback.md': {
      routes:
        | '/framework/feedback'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/framework/get-framework.md': {
      routes:
        | '/framework/get-framework'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/framework/open-source.md': {
      routes:
        | '/framework/open-source'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
